/*
=========================================================
1. REVENUE ANALYSIS
=========================================================
*/

-- Total revenue generated by Olist

SELECT
    ROUND(SUM(p.payment_value), 2) AS total_revenue
FROM orders AS o
JOIN payments AS p
    ON o.order_id = p.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable');


-- Total revenue by quarter

SELECT
    YEAR(o.order_purchase_timestamp) AS order_year,
    QUARTER(o.order_purchase_timestamp) AS order_quarter,
    ROUND(SUM(p.payment_value), 2) AS total_revenue
FROM orders AS o
JOIN payments AS p
    ON o.order_id = p.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable')
GROUP BY
    YEAR(o.order_purchase_timestamp),
    QUARTER(o.order_purchase_timestamp)
ORDER BY
    order_year,
    order_quarter;


-- Total revenue by month

SELECT
    YEAR(o.order_purchase_timestamp) AS order_year,
    MONTH(o.order_purchase_timestamp) AS order_month,
    ROUND(SUM(p.payment_value), 2) AS total_revenue
FROM orders AS o
JOIN payments AS p
    ON o.order_id = p.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable')
GROUP BY
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)
ORDER BY
    order_year,
    order_month;

/*
=========================================================
2. ORDER ANALYSIS
=========================================================
*/

-- Total number of orders

SELECT
    COUNT(order_id) AS number_of_orders
FROM orders
WHERE order_status NOT IN ('canceled', 'unavailable');


-- Number of orders by month

SELECT
    YEAR(order_purchase_timestamp) AS order_year,
    MONTH(order_purchase_timestamp) AS order_month,
    COUNT(*) AS number_of_orders
FROM orders
WHERE order_status NOT IN ('canceled', 'unavailable')
GROUP BY
    YEAR(order_purchase_timestamp),
    MONTH(order_purchase_timestamp)
ORDER BY
    order_year,
    order_month;

/*
=========================================================
3. PRODUCT CATEGORY ANALYSIS
=========================================================
*/

-- Total sales by product category

SELECT
    pc.product_category_name_english,
    ROUND(SUM(oi.price), 2) AS total_sales
FROM orders AS o
JOIN order_items AS oi
    ON o.order_id = oi.order_id
JOIN products AS pr
    ON oi.product_id = pr.product_id
JOIN product_category_translation AS pc
    ON pr.product_category_name = pc.product_category_name
WHERE o.order_status NOT IN ('canceled', 'unavailable')
GROUP BY
    pc.product_category_name_english
ORDER BY
    total_sales DESC;

/*
=========================================================
4. AVERAGE ORDER VALUE (AOV) ANALYSIS
=========================================================
*/

-- Overall Average Order Value

SELECT
    ROUND(AVG(p.payment_value), 2) AS average_order_value
FROM payments AS p
JOIN orders AS o
    ON p.order_id = o.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable');


-- Average Order Value by payment type

SELECT
    p.payment_type,
    ROUND(AVG(p.payment_value), 2) AS average_order_value
FROM payments AS p
JOIN orders AS o
    ON p.order_id = o.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable')
GROUP BY
    p.payment_type
ORDER BY
    average_order_value DESC;


-- Average Order Value by Product Category

WITH order_totals AS (
    SELECT
        p.order_id,
        SUM(p.payment_value) AS order_total
    FROM payments AS p
    GROUP BY p.order_id
),

order_categories AS (
    SELECT DISTINCT
        oi.order_id,
        pc.product_category_name_english
    FROM order_items AS oi
    JOIN products AS pr
        ON oi.product_id = pr.product_id
    JOIN product_category_translation AS pc
        ON pr.product_category_name = pc.product_category_name
)

SELECT
    oc.product_category_name_english,
    ROUND(AVG(ot.order_total), 2) AS average_order_value
FROM order_totals AS ot
JOIN orders AS o
    ON ot.order_id = o.order_id
JOIN order_categories AS oc
    ON ot.order_id = oc.order_id
WHERE o.order_status NOT IN ('canceled', 'unavailable')
GROUP BY
    oc.product_category_name_english
ORDER BY
    average_order_value DESC;
